### ISSUE TITLE
Unable to set preferable language to Traditional Chinese (zh-TW)

### ISSUE THREAD

**Issue by jimewu** [kenCode-de/smartcoins-wallet#29]
When I set  preferable language to Traditional Chinese, it only shows English

**Comment by kenCode-de** [comment]
I think that is probably due to a language code issue. In the software, we have zh-TW, and cmn-Hant-TW as the codes for Cantonese. Does your phone have another code that it is looking for? 
 
I see we have the folder name set to this: 
https://github.com/kenCode-de/smartcoins-wallet/tree/master/app/src/main/res/values-zh-rTW 
 
If you can, please see which language code your phone is set to, and let me know here. 
Thanx in advance @jimewu :)

**Comment by jimewu** [comment]
Yes, I do noticed that there is a values-zh-rTW folder there for the Traditional Chinese, and according to this article (http://goo.gl/xmaior), **the Chinese folders for China, Taiwan, and Hong Kong should be:
China: values-zh-rCN
Taiwan: values-zh-rTW
Hong Kong: values-zh-rHK**

so I guess it is the "values-zh" for China should be renamed to "values-zh-rCN", or the "values-zh-rTW" will not be taken.

Screenshot#1: my android is set to Traditional Chinese
http://imgur.com/a/8YqDs

Screenshot#2: setting my wallet to zh-TW doest not give me the Traditional Chinese interface:
http://imgur.com/a/WwFGW

Screenshot#3: while setting my wallet to zh doest give me the Simplified Chinese interface for China:
http://imgur.com/a/H0Bci

**Comment by kenCode-de** [comment]
Please make sure you have a backup of your Brainkey and TRIPLE CHECK it. 
Then make sure you have your smartcoins wallet .bin file backed up too. 
Somewhere safe. 
 
THEN un-install smartcoins wallet. 
Then install v1.0.5 beta1 from this apk: 
https://drive.google.com/file/d/0ByqWLK0d_xq0cWItU2xBOEVnU2s/view?usp=sharing

Then see if Traditional Chinese will load now... 
 
Please and thanx jimewu :)

**Comment by jimewu** [comment]
I installed the new version in a clean Android, and the account creation page is still in simplified Chinese. After I filled in the account name, password and click the button, it stuck in the circle, so I can not see the further pages.

**Comment by kenCode-de** [comment]
Ok, I hope we fixed this for you. 
#1 Backup your Brainkey and TRIPLE check to make sure it is accurate. 
#2 Backup your .bin file as well, and make sure that file is somewhere safe. 
#3 Never forget your PIN number! 
#4 Uninstall Smartcoins Wallet completely. 
#5 Install this v1.0.5 beta2: 
https://drive.google.com/file/d/0ByqWLK0d_xq0LVo5c0gzV0xYd1E/view?usp=sharing 
#6 let me know if the bug has been fixed... 
 
Please and thanx in advance! :)

**Comment by jimewu** [comment]
It worked with some minor issue:
1. the wallet still stuck in the first run at account creation, but after reboot my android it is ok.
2. the wallet did not recognize my language by default, but when I set it to zh-TW, it worked.
3. some term is kind of awkward. As a notice, common terms in Simplified and Traditional Chinese could be different.

But still it finally worked, so thanks a lot.

**Comment by kenCode-de** [comment]
Thank you jimewu, we will look at fixing #1 and #2 today and try to have them done for you too. As for #3, the languages can be edited right here on github, so we will try to get those values avaiable for editing in the next day or two as well. Thank you so much for your patience, I am doing my very best to make it perfect :)

**Comment by kenCode-de** [comment]
I think we have addressed all issues in the latest release. Please see the post about it here and thank you so much @jimewu for giving it a try :) 
 
https://steemit.com/crypto-news/@kencode/ann-smartcoins-wallet-v1-0-5-released-multiple-currencies-loyalty-points-3sec-transactions-44-languages-overdraft-protection
