### ISSUE TITLE
I find a bug in smartcoins wallet

### ISSUE THREAD

**Issue by yuli7376** [kenCode-de/smartcoins-wallet#30]
I can send bts or bitcny，but I can not send jinbi，the error message is ‘unable to sent the amount’

**Comment by kenCode-de** [comment]
Thank you @yuli7376 that is a known issue and should be fixed in the next version release :) 
issue: https://github.com/kenCode-de/smartcoins-wallet/issues/15 
 
Thank you for your input! :)
