### ISSUE TITLE
History

### ISSUE THREAD

**Issue by rules169** [kenCode-de/smartcoins-wallet#39]
My first payment  (that i received) showed up 5 times in the list. I don't know if this is on purpose or not?

**Comment by kenCode-de** [comment]
Ok, I hope we fixed this for you. 
#1 Backup your Brainkey and TRIPLE check to make sure it is accurate. 
#2 Backup your .bin file as well, and make sure that file is somewhere safe. 
#3 Never forget your PIN number! 
#4 Uninstall Smartcoins Wallet completely. 
#5 Install this v1.0.5 beta2: 
https://drive.google.com/file/d/0ByqWLK0d_xq0LVo5c0gzV0xYd1E/view?usp=sharing 
#6 let me know if the bug has been fixed... 
 
Please and thanx in advance! :)

**Comment by kenCode-de** [comment]
I think we have addressed all issues in the latest release. Please see the post about it here and thank you so much @rules169 for giving it a try :) 
 
https://steemit.com/crypto-news/@kencode/ann-smartcoins-wallet-v1-0-5-released-multiple-currencies-loyalty-points-3sec-transactions-44-languages-overdraft-protection
