### ISSUE TITLE
When Press send button,crash happen 

### ISSUE THREAD

**Issue by name55** [kenCode-de/smartcoins-wallet#44]

**Comment by kenCode-de** [comment]
Phone? Model? Android version? Behind firewall? Going through VPN? WSS (secure websockets) blocked? 
 
Give me all of the details so that I can reproduce the problem. 
Please and thanx :)

**Comment by kenCode-de** [comment]
I think we have addressed all issues in the latest release. Please see the post about it here and thank you so much @name55 for giving it a try :) 
 
https://steemit.com/crypto-news/@kencode/ann-smartcoins-wallet-v1-0-5-released-multiple-currencies-loyalty-points-3sec-transactions-44-languages-overdraft-protection
