### ISSUE TITLE
Error in calculation open.eth

### ISSUE THREAD

**Issue by webkracht** [kenCode-de/smartcoins-wallet#49]
I have 8.5688 open.eth in my wallet.
It shows a value of 856.88 Euro

**Comment by kenCode-de** [comment]
Wow, that's weird. Can you send me a little screenshot so we can see if this is a rounding issue or an "equivalent value" issue? Images really help the devs. Thanx a bunch :)

**Comment by kenCode-de** [comment]
Ok, I think we got that display fixed, please try out the new version, I hope you like it :) 
https://play.google.com/store/apps/details?id=de.bitsharesmunich.smartcoinswallet 
 
Thank you for the issue report! :)
