### ISSUE TITLE
UIA Transaction Failure

### ISSUE THREAD

**Issue by maemon** [kenCode-de/smartcoins-wallet#5]
As reviewed on Google Play, transaction on User Issued Asset doesn't seem to be working. Whenever I try to send an Asset I created, it says "No Internet Connection". 
The Issue is not present while sending BTS.

I am using a HTC 10 with Android 6.0.1

**Comment by kenCode-de** [comment]
We should have a fix for this by end of day tomorrow (thursday) for you :) 
Once done and tested, we will upload v1.0.2 to google play for you to make sure it was fixed. 
Thanx for the report! :)

**Comment by maemon** [comment]
No probs, looking forward to it!

**Comment by kenCode-de** [comment]
Update: I think we fixed it. Was gonna push the release to google play tonight but it's just too late right now. Will make some other tweaks tomorrow then hopefully publish v1.0.2 tomorrow night.

**Comment by kenCode-de** [comment]
Closing this issue now, will release (hopefully) v1.0.2 tonight..
