### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by appbound** [kenCode-de/smartcoins-wallet#50]
Android Version 4.4.2

Great app btw.

I'm in the USA.

CONSISTENTLY recieving error: your system does not support new ssl ciphering error : fatal alert received handshake failure

**Comment by appbound** [comment]
When I hit send it hard crashes.

**Comment by kenCode-de** [comment]
Smartcoins Wallet requires Android 5 or higher (Lollipop) even though Google Play says 4.x, not sure why. Smartcoins Wallet uses Secure Web Sockets (wss), which are only supported by Android 5 or higher. Sorry, wish I had better news for you :( We have contacted Google Play about this, but to no avail.
