### ISSUE TITLE
The wallet(v1.0.5 beta) list all assets 

### ISSUE THREAD

**Issue by yuli7376** [kenCode-de/smartcoins-wallet#52]
The wallet(v1.0.5 beta) list all assets ,include 0 banlances? I think it is terrible.

**Comment by christoph3** [comment]
Can anybody explain the smartcoins wallet? Lol

**Comment by kenCode-de** [comment]
If you are using a beta, please update to the latest version and/or set the app to update itself in the google play store settings. I hope that helps :)
