### ISSUE TITLE
Provide pure floss build flavor

### ISSUE THREAD

**Issue by krt16s** [kenCode-de/smartcoins-wallet#68]
Crashlytics is a proprietary, non-free build dependency. Could you provide a build flavor that does not require it?

**Comment by kenCode-de** [comment]
Yep, we certainly will. There were some weird crash reports from people with odd phones and we really needed an easier way to figure out how to help those people. Anyway, the developers will definitely remove crashlytics asap. Probably in the next version release. Sorry for any inconvenience.
