### ISSUE TITLE
Can't send Bitshares from my wallet

### ISSUE THREAD

**Issue by jamestrader9** [kenCode-de/smartcoins-wallet#77]
Hello, I am having trouble with my smartcoins wallet for android.
I can't send 'bitshares coins'.
When I try to send them the send button won't work. The button is grey, not like the picture on the appstore where it is red. 
There is a green tick at bottom of screen beside the blocks so connectivity shouldn't be an issue.

Can you please help me with this?

**Comment by computationalcore** [comment]
Sure, can you send screenshots, account name and device info to computationalcore@gmail.com? Also I may need some logs later.

**Comment by jamestrader9** [comment]
okay sending now
